on: pull_request

name: bump-versions
jobs:
  bump-versions:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.pull_request.head.ref || github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         ref: ${{ env.BRANCH_NAME }}
         fetch-depth: 0
      - name: Edit file
        run: ./scripts/update_version.sh ${{ env.BRANCH_NAME }}
      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "bot@rudderstack.com"
          git config user.name "Github Action"
          git add . && git commit --amend --no-edit && git push origin HEAD:${{ env.BRANCH_NAME }} -f
